name: pythoncryptex

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80

  db:
    container_name: db
    image: postgres:latest
    env_file:
      - test.env
    ports:
      - 8001:5432