name: pythoncryptex

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=CryptexAPI
      - POSTGRES_PASSWORD=CryptexAPI
    ports:
      - 8001:5432