services:
  api:
    container_name: cryptex-api-python
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    networks:
      - api

  db:
    container_name: cryptex-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=CryptexAPI
      - POSTGRES_PASSWORD=CryptexAPI
    ports:
      - 8001:5432
    networks:
      - api

networks:
  api:
    driver: bridge