name: pythoncryptex

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:latest
    env_file:
      - src/cryptexapi.env
    ports:
      - 8001:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 30s
      retries: 5