# Test your FastAPI endpoints

POST http://127.0.0.1:8000/players/test_id?name=test_name
Accept: application/json

###

GET http://127.0.0.1:8000/puzzles/test_id?difficulty=1
Accept: application/json

###

PUT http://127.0.0.1:8000/puzzles/test_id?solution=TEST
Accept: application/json

###

GET http://127.0.0.1:8000/players/test_id
Accept: application/json

###